### ISSUE TITLE
trip data not updated since october

### ISSUE THREAD

**Issue by astrakid** [Newan/ioBroker.bluelink#175]
hi,
my trip data (kia niro ev sg2) is not updated anymore in iobroker.
but when using https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor i get trip data.
can you check that?

regards,
andre

**Comment by arteck** [comment]
fixed in new version

**Comment by astrakid** [comment]
adapter doesn't start with 3.1.1:

`2025-01-08 09:46:47.213 - error: bluelink.0 (887616) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2025-01-08 09:46:47.215 - error: bluelink.0 (887616) unhandled promise rejection: The state contains the forbidden properties day, time!
2025-01-08 09:46:47.216 - error: bluelink.0 (887616) Error: The state contains the forbidden properties day, time!
at Validator.validateSetStateObjectArgument (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/validator.js:299:13)
at Bluelink._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:4985:21)
at Bluelink.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:4963:17)
at Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:133:30)
at async Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:97:21)
at async Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:97:21)
at async Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:97:21)
at async Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:97:21)
at async Bluelink.readStatusVin (/opt/iobroker/node_modules/iobroker.bluelink/main.js:391:17)
at async Bluelink.readStatus (/opt/iobroker/node_modules/iobroker.bluelink/main.js:355:13)
2025-01-08 09:46:47.216 - error: bluelink.0 (887616) The state contains the forbidden properties day, time!
2025-01-08 09:46:47.218 - warn: bluelink.0 (887616) Terminated (UNCAUGHT_EXCEPTION): Without reason
2025-01-08 09:46:47.220 - error: bluelink.0 (887616) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2025-01-08 09:46:47.220 - error: bluelink.0 (887616) unhandled promise rejection: The state contains the forbidden properties day, time!
2025-01-08 09:46:47.220 - error: bluelink.0 (887616) Error: The state contains the forbidden properties day, time!
at Validator.validateSetStateObjectArgument (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/validator.js:299:13)
at Bluelink._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:4985:21)
at Bluelink.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/cjs/lib/adapter/adapter.js:4963:17)
at Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:133:30)
at async Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:97:21)
at async Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:97:21)
at async Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:97:21)
at async Json2iob.parse (/opt/iobroker/node_modules/iobroker.bluelink/lib/json2iob.js:97:21)
at async Bluelink.readStatusVin (/opt/iobroker/node_modules/iobroker.bluelink/main.js:391:17)
at async Bluelink.readStatus (/opt/iobroker/node_modules/iobroker.bluelink/main.js:355:13)
2025-01-08 09:46:47.220 - error: bluelink.0 (887616) The state contains the forbidden properties day, time!
2025-01-08 09:46:47.722 - error: bluelink.0 (887616) Cannot check object existence of "bluelink.0.KN************0276.vehicleStatusRaw.vehicleStatus.steerWheelHeat": DB closed
2025-01-08 09:46:47.722 - warn: bluelink.0 (887616) Could not perform strict object check of state bluelink.0.KN************0276.vehicleStatusRaw.vehicleStatus.hoodOpen: DB closed
2025-01-08 09:46:47.723 - warn: bluelink.0 (887616) get state error: Connection is closed.
2025-01-08 09:46:47.723 - error: bluelink.0 (887616) Error extract objectKeys: KN************0276.vehicleStatusRaw.vehicleStatus.[object Object]
2025-01-08 09:46:47.723 - error: bluelink.0 (887616) Error: Could not check object existence of bluelink.0.KN************0276.vehicleStatusRaw.vehicleStatus.steerWheelHeat: Cannot check object existence of "bluelink.0.KN************0276.vehicleStatusRaw.vehicleStatus.steerWheelHeat": DB closed
2025-01-08 09:46:47.724 - error: bluelink.0 (887616) Cannot check object existence of "bluelink.0.KN************0276.vehicleStatusRaw.vehicleStatus.sideBackWindowHeat": Connection is closed.
2025-01-08 09:46:47.725 - error: bluelink.0 (887616) Error extract objectKeys: KN************0276.vehicleStatusRaw.vehicleStatus.[object Object]
2025-01-08 09:46:47.725 - error: bluelink.0 (887616) Error: Could not check object existence of bluelink.0.KN************0276.vehicleStatusRaw.vehicleStatus.sideBackWindowHeat: Cannot check object existence of "bluelink.0.KN************0276.vehicleStatusRaw.vehicleStatus.sideBackWindowHeat": Connection is closed.
2025-01-08 09:46:47.796 - error: host.eef9688f3a59 instance system.adapter.bluelink.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
`

**Comment by astrakid** [comment]
ok. installed 2.3.6 again and i get trip data. thx a lot!!!
